version: "3"
networks:
  mbr_test_network_1:
    driver: bridge

services:
  mbr_gateway:
    privileged: true
    restart: unless-stopped
    image: openresty/openresty:1.19.9.1-14-focal
    # image: zesty:v0.0.1
    container_name: mbr_gateway
    networks:
      - mbr_test_network_1

    #image: massbit/massbitroute_gateway

    # command: 'sleep infinity'
    # command: ""
    # network_mode: "host"
    ports:
      - 80:80
    volumes:
       - ./volume/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
       - ./volume/modules.conf:/usr/local/openresty/nginx/conf/modules.conf
       - ./volume/conf:/usr/local/openresty/nginx/conf/include:rw
       - ./volume/conf/subconf:/usr/local/openresty/nginx/conf/subconf:rw
       - ./volume/data:/usr/local/openresty/nginx/data:rw
       - ./volume/logs:/usr/local/openresty/nginx/logs:rw
       - ./volume/modules:/usr/local/openresty/nginx/extensions:rw
       - ./volume/tmp:/usr/local/openresty/nginx/tmp:rw
       - ./volume/scripts:/usr/local/openresty/scripts:rw
    environment:
      - MBR_ENV=keiko
      - ID=
      - USER_ID=
      - BLOCKCHAIN=
      - NETWORK
      - ZONE=
      - APP_KEY=
      - INSTALL_CMD=

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - mbr_test_network_1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
