version: '3'

services:
  dev:
    container_name: massbitroute-cli
    image: massbitroute-cli:1.0.0
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: sleep infinity
    ports: 
    - "9000:80"
    volumes:
      - .:/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  default:
    driver: bridge
