version: '3'

services:
  massbitroute-cli:
    container_name: massbitroute-cli
    image: massbitroute-cli:1.0.0
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_ENV=uat
    command: sleep infinity
    ports: 
    - "9000:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge
