version: '3'

services:
  massbitroute-cli:
    container_name: massbitroute-cli
    image: massbitroute-cli:1.0.0
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_ENV=uat
        - TARGET_OS=linux
        - TARGET_ARCHITECTURE=amd64
    # command: sleep infinity
    ports: 
    - "9000:80"
    volumes:
      - .:/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  default:
    driver: bridge
